// <auto-generated />
namespace AluguerCarros.Migrations.AlugarCarros
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Datas_Requisicoes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Datas_Requisicoes));
        
        string IMigrationMetadata.Id
        {
            get { return "201808221712423_Datas_Requisicoes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
