// <auto-generated />
namespace AluguerCarros.Migrations.AlugarCarros
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Pedido_Avaliacoes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pedido_Avaliacoes));
        
        string IMigrationMetadata.Id
        {
            get { return "201808240025298_Pedido_Avaliacoes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
