// <auto-generated />
namespace AluguerCarros.Migrations.AlugarCarros
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Carro_Marca_Modelo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Carro_Marca_Modelo));
        
        string IMigrationMetadata.Id
        {
            get { return "201808221454011_Carro_Marca_Modelo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
